cio using the .c -> .ll -> .mir -> .o pipeline now.
ciocc saving state in %.ciocc files for use by cio

diff --git a/cio b/cio
--- a/cio
+++ b/cio
@@ -1,7 +1,12 @@
 #!/bin/bash
 
 # SET BY USER
-CC=`realpath ~/llvm-project/build/bin/clang`
+OUR_LLVM_BINARIES=`realpath ~/llvm-project/build/bin`
+CLANG="$OUR_LLVM_BINARIES/clang" # need the underlying clang driver that ciocc uses
+LLC="$OUR_LLVM_BINARIES/llc"
+LLVM_MC="$OUR_LLVM_BINARIES/llvm-mc"
+CIOCC=`realpath ./ciocc`
+CC="$CIOCC"
 CHECKER_PLUGIN_PATH=`realpath ./checker/bap/interval/`
 
 # cio defaults
@@ -41,7 +46,7 @@ function usage
 			  
 	       	 --config-file and crypto_project_dir_root are required arguments. If they are not passed,
                  the defaults of ${CC} and $(pwd) are used respectively."
-    exit 2
+    exit 1
 }
 
 PARSED_ARGS=$(getopt -o "hc:p:b:o:f:e:p:t:j:" -l "help,cc:,checker-plugin-path:,build-dir:,big-obj:,config-file:,checker-flags:,cflags:,crypto-dir:,is-libsodium,ss,cs,nosymex" -n $TOOLNAME -- "$@")
@@ -149,57 +154,65 @@ if [[ $? -ne 0 ]]; then
     echo -e "\t3. opam install bap"
     echo -e "\t4. opam install bap-primus-symbolic-executor"
     echo -e '\t5. eval $(opam env)'
-    exit 3
+    exit 2
 fi
 
-if [[ DO_SYMEX -eq 1 ]]; then
+if [[ "$DO_SYMEX" -eq 1 ]]; then
     CHECKER_SYMEX_FLAGS=""
 else
     CHECKER_SYMEX_FLAGS="--uarch-checker-no-symex"
 fi
 
-if [[ MITIGATE_CS -eq 0 ]]; then
+if [[ "$MITIGATE_CS" -eq 0 ]]; then
     CHECKER_CS_FLAGS=""
     CC_CS_FLAGS=""
+    LLC_CS_FLAGS=""
 else
     CHECKER_CS_FLAGS="--uarch-checker-cs"
     CC_CS_FLAGS="-mllvm --x86-cs -mllvm --x86-cs-csv-path=${CHECKER_ALERTS_CSV}"
+    LLC_CS_FLAGS="--x86-cs --x86-cs-csv-path=${CHECKER_ALERTS_CSV}"
 fi
 
-if [[ MITIGATE_SS -eq 0 ]]; then
+if [[ "$MITIGATE_SS" -eq 0 ]]; then
     CHECKER_SS_FLAGS=""
     CC_SS_FLAGS=""
+    LLC_SS_FLAGS=""
 else
     CHECKER_SS_FLAGS="--uarch-checker-ss"
     CC_SS_FLAGS="-mllvm --x86-ss -mllvm --x86-ss-csv-path=${CHECKER_ALERTS_CSV}"
+    LLC_SS_FLAGS="--x86-ss --x86-ss-csv-path=${CHECKER_ALERTS_CSV}"
 fi
 
+
+# need to set cio to a known-good state, so clean, re-configure
 make --directory=$TARGET_DIR clean
 
 pushd .
-cd $TARGET_DIR; ./configure CC=$CC
+# need the underlying clang driver that ciocc uses in configure.
+# ciocc currently does not work here
+cd $TARGET_DIR; ./configure CC=$CLANG
 CONFIG_RES=$?
 popd
 
 if [[ $CONFIG_RES -ne 0 ]]; then
     echo "Error running ./configure in $TARGET_DIR. $TOOLNAME exiting."
-    exit 5
+    exit $CONFIG_RES
 fi
 
+
+
 # make the dir to hold all of the build artifacts
-echo -n "Creating ${TOOLNAME} build dir ${BUILD_DIR}..."
+echo "Creating ${TOOLNAME} build dir ${BUILD_DIR}..."
 if [[ -e $BUILD_DIR ]]; then
-    echo -n it already exists, removing old build dir first...
+    echo it already exists, removing old build dir first...
     rm -r $BUILD_DIR
 fi
 mkdir $BUILD_DIR
 echo done
 
-DRY_RUN_LOG=$BUILD_DIR/initial_make_dry_run.log
-echo "Putting 'make --dry-run' output into $DRY_RUN_LOG"
-make -j 1 --directory=$TARGET_DIR CC=$CC  --dry-run > $DRY_RUN_LOG 2>&1
 
-echo -n "Running target\'s makefile..."
+
+echo "Running target's makefile: make -j 32 --directory=$TARGET_DIR CC=$CC"
 make -j 32 --directory=$TARGET_DIR CC=$CC
 COMPILE_PASS_RES=$?
 # echo compile_pass_res is $COMPILE_PASS_RES
@@ -207,45 +220,66 @@ echo done
 
 if [[ $COMPILE_PASS_RES -ne 0 ]]; then
     echo "Error running $TOOLNAME initial compilation pass. $TOOLNAME exiting."
-    exit 6
+    exit $COMPILE_PASS_RES
 fi
+
+
 
 if [[ $IS_LIBSODIUM -eq 1 ]]; then
     echo 'init sodium_init' > $CONFIG_FILE
 fi
 
+
+
 # put all per-function secret csv contents into one big  csv file
-# echo -n "Gathering all per-function secret csv files into ${ALL_SECRETS_CSV}..."
+# echo "Gathering all per-function secret csv files into ${ALL_SECRETS_CSV}..."
 find $TARGET_DIR -name '*secrets.csv' -a ! -empty | xargs -I '{}' cat '{}' >> $CONFIG_FILE
 GATHER_SECRETS_RES=$?
 echo done
 
 if [[ $GATHER_SECRETS_RES -ne 0 ]]; then
     echo "Error gathering all per-function secret csv files into one. $TOOLNAME exiting."
-    exit 7
+    exit $GATHER_SECRETS_RES
 fi
 
-echo -n "Cleaning up per-function secret csv files..."
+echo "Cleaning up per-function secret csv files..."
 find $TARGET_DIR -name '*secrets.csv' -a ! -path "*${BUILD_DIR}*" -delete
 echo done
 
+
+
 # put all the object files into one big object file
-echo -n "Gathering all intermediate object files into ${BIG_OBJ}..."
-find $TARGET_DIR -name '*.o' -a ! -path '*.libs*' | xargs ld -O0 -o $BIG_OBJ -lc
-BUILD_BIG_OBJ_RES=$?
-echo done
+if [[ "$IS_LIBSODIUM" -eq 1 ]]; then
+    source $TARGET_DIR/src/libsodium/libsodium.la
+    LIBNA_SHARED_LIB=$(find $TARGET_DIR -name "$dlname")
+    BUILD_BIG_OBJ_RES=$?
+    if [[ "$BUILD_BIG_OBJ_RES" -eq 0 ]]; then
+	cp $LIBNA_SHARED_LIB $BIG_OBJ
+    fi
+else
+    echo "Gathering all intermediate object files into ${BIG_OBJ}..."
+    find $TARGET_DIR -name '*.o' -a ! -path '*.libs*' | xargs ld -O0 -o $BIG_OBJ -lc
+    BUILD_BIG_OBJ_RES=$?
+    echo done
+fi
 
 if [[ $BUILD_BIG_OBJ_RES -ne 0 ]]; then
     echo "Error jamming all separate object files into one for use by checker. $TOOLNAME exiting."
-    exit 8
+    exit $BUILD_BIG_OBJ_RES
 fi
+
+
 
 echo "SHA256 of pre-mitigation $BIG_OBJ is:"
 echo $(sha256sum $BIG_OBJ)
 
+
+
 echo Dumping BIR and DKNOWLEDGE into $BUILD_DIR/jammed.together.dbir.txt
 bap -dbir --no-optimization --bil-optimization=0 $BIG_OBJ &> $BUILD_DIR/jammed.together.dbir.txt
 bap -dknowledge --no-optimization --bil-optimization=0 $BIG_OBJ >> $BUILD_DIR/jammed.together.dbir.txt 2>&1
+
+
 
 echo "Starting checker on ${BIG_OBJ} using secrets file ${ALL_SECRETS_CSV}"
 echo "Start time is: $(TZ='America/Los_angeles' date +%T-%Z)"
@@ -263,73 +297,60 @@ bap \
     $BIG_OBJ > $BAP_LOGS 2>&1
 echo "Done checking $BIG_OBJ at $(TZ='America/Los_angeles' date +%T-%Z)"
 
-echo -n Cleaning up build artifacts from compilation,checking pass...
-make --directory=$TARGET_DIR clean
-echo done
 
-echo "Transforming instructions in the following functions:"
-# first field of each csv record has the double quoted sub name
-HARDEN_FUNCS=$(tail -n +2 $CHECKER_ALERTS_CSV | gawk --field-separator="," '{ print $1 }' - | uniq)
 
-for func in $HARDEN_FUNCS; do
-    echo $func
+ALL_MIR_FILES=$(find $TARGET_DIR -iname '*.mir')
+for MIR_FILE in $ALL_MIR_FILES; do
+    CIOCC_COMPILATION_FILE=${MIR_FILE/%.mir/.ciocc}
+    if [[ ! (-e "$CIOCC_COMPILATION_FILE") ]]; then
+	echo "ciocc metadata file for MIR file $MIR_FILE doesn't exist"
+	exit 3
+    fi
+    # this source provides definitions for ASM_FILE, MIR_FILE, OBJ_FILE 
+    source "$CIOCC_COMPILATION_FILE"
+    echo "$LLC --relocation-model=pic $LLC_SS_FLAGS $LLC_CS_FLAGS $MIR_FILE -o $ASM_FILE"
+    $LLC --relocation-model=pic "$LLC_SS_FLAGS" "$LLC_CS_FLAGS" $MIR_FILE -o $ASM_FILE
+    echo "$LLVM_MC --position-independent $ASM_FILE -filetype=obj -o $OBJ_FILE"
+    $LLVM_MC --position-independent $ASM_FILE -filetype=obj -o $OBJ_FILE
 done
 
-# debugging: check that each sub is outputted the same, same SHA256 hash?
-# make --directory=$TARGET_DIR clean
-make --directory=$TARGET_DIR CC=$CC -j ${NUM_MAKE_JOB_SLOTS}
-find $TARGET_DIR -name '*.o' -a ! -path '*.libs*' | xargs ld -O0 -o $BIG_OBJ.second.time.o -lc
-echo $HARDEN_FUNCS | while read -r func
-do
-    echo Checking if func $func differs...
-    ORIG_CONTENTS=$(objdump --disassemble=$func $BIG_OBJ | tail -n +3)
-    NEW_CONTENTS=$(objdump --disassemble=$func $BIG_OBJ.second.time.o | tail -n +3)
-    ORIG_CONTENTS_HASH=$(echo $ORIG_CONTENTS | sha256sum -)
-    NEW_CONTENTS_HASH=$(echo $NEW_CONTENTS | sha256sum -)
-    test "$NEW_CONTENTS_HASH" != "$ORIG_CONTENTS_HASH" && echo "Disassembly for fn symbol $func differs"
-done
 
-# TODO, this should be llc with just our passes which would get rid of our
-# need to have to play nice with the crypto lib's CFLAGS.
-# ideally, they would use `override CFLAGS += ...`
-# instead of `CFLAGS=...`, so then we can use the comamnd
-# line to append to their CFLAGS, but instead, we have to
-# check if they use override or not and handle each case separately
-# IMPORTANT: iirc, if both SS and CS flags are specified to the compiler, then SS must come before the CS flags
-grep -E 'override CFLAGS' ${TARGET_DIR}/Makefile
-NO_OVERRIDE=$?
-if [[ NO_OVERRIDE -eq 0 ]]; then
-    # has override, we are fine
-    FINAL_CFLAGS="$CC_SS_FLAGS $CC_CS_FLAGS $EXTRA_CFLAGS"
-else
-    # get the cflags manually
-    # awk: find the line of their makefile that starts with CFLAGS\s*= or CFLAGS= and grab the stuff after
-    # THEIR_CFLAGS=$(awk -F"( = )|(=)| " '$1 ~ /^CFLAGS$/ { ORS=" "; for (i = 3; i <= NF; i++) print $i }' ${TARGET_DIR}/Makefile)
-    THEIR_CFLAGS=$(awk '$1 ~ /^CFLAGS$/ { ORS=" "; for (i = 3; i <= NF; i++) print $i }' ${TARGET_DIR}/Makefile)
-    FINAL_CFLAGS="$CC_SS_FLAGS $CC_CS_FLAGS $THEIR_CFLAGS $EXTRA_CFLAGS"
-fi
 
-echo -n Running mitigation pass...
-echo -n TODO, this should be llc with just our passes...
-echo final_cflags are $FINAL_CFLAGS
-export CFLAGS=$FINAL_CFLAGS
-make --directory=$TARGET_DIR clean
-make CFLAGS="$FINAL_CFLAGS" --environment-overrides --directory="$TARGET_DIR" CC=$CC -j $NUM_MAKE_JOB_SLOTS
-MITIGATION_PASS_RES=$?
-echo done
+# after regenerating the object files, the shared libraries should be out of
+# date, so running make should regenerate these automagically
+# don't need to use ciocc here
+make --directory="$TARGET_DIR" CC="$CLANG" -j "$NUM_MAKE_JOB_SLOTS"
 
-if [[ $MITIGATION_PASS_RES -ne 0 ]]; then
-    echo "Error applying mitigation transforms in $TARGET_DIR. $TOOLNAME exiting."
-    exit 9
-fi
+
 
 # put all the object files into one big object file again
-echo -n "Gathering all intermediate object files into ${BIG_OBJ}..."
-find $TARGET_DIR -name '*.o' -a ! -path '*.libs*' | xargs ld -O0 -o ${BIG_OBJ}.verification.o -lc
-BUILD_BIG_OBJ_RES=$?
-echo done
+if [[ "$IS_LIBSODIUM" -eq 1 ]]; then
+    source "$TARGET_DIR/src/libsodium/libsodium.la"
+    LIBNA_SHARED_LIB=$(find "$TARGET_DIR" -name "$dlname")
+    BUILD_BIG_OBJ_RES=$?
+    if [[ "$BUILD_BIG_OBJ_RES" -eq 0 ]]; then
+	cp "$LIBNA_SHARED_LIB" "$BIG_OBJ.verification.o"
+    fi
+else
+    echo "Gathering all intermediate object files into ${BIG_OBJ}..."
+    find "$TARGET_DIR" -name '*.o' -a ! -path '*.libs*' | xargs ld -O0 -o "$BIG_OBJ.verification.o" -lc
+    BUILD_BIG_OBJ_RES=$?
+    echo done
+fi
 
-echo -n Running verification pass...
+if [[ "$BUILD_BIG_OBJ_RES" -ne 0 ]]; then
+    echo "Error jamming all separate object files into one for use by checker. $TOOLNAME exiting."
+    exit $BUILD_BIG_OBJ_RES
+fi
+
+
+
+echo "SHA256 of post-mitigation $BIG_OBJ.verification.o is:"
+echo $(sha256sum "$BIG_OBJ.verification.o")
+
+
+
+echo Running verification pass...
 echo "Start time is: $(TZ='America/Los_angeles' date +%T-%Z)"
 echo "logging to ${BAP_LOGS}"
 bap \
@@ -346,8 +367,10 @@ bap \
 echo "Done checking $BIG_OBJ at $(TZ='America/Los_angeles' date +%T-%Z)"
 echo done
 
-if [[ $IS_LIBSODIUM -eq 1 ]]; then
-    echo -n "Running libsodium unit tests..."
-    make --directory=$TARGET_DIR check
+
+
+if [[ "$IS_LIBSODIUM" -eq 1 ]]; then
+    echo "Running libsodium unit tests..."
+    make -j 32 --directory="$TARGET_DIR" check
     echo done
 fi
