clean up some cio script stuff. for now, prefer using the config file over the annotated secrets files. TODO: use both where the config file just has one line: `init sodium_init` and the rest of the lines come from annotated secrets scraping

diff --git a/cio b/cio
--- a/cio
+++ b/cio
@@ -199,15 +199,15 @@ if [[ $IS_LIBSODIUM -eq 1 ]]; then
 fi
 
 # put all per-function secret csv contents into one big  csv file
-echo -n "Gathering all per-function secret csv files into ${ALL_SECRETS_CSV}..."
-find $TARGET_DIR -name '*secrets.csv' -a ! -empty | xargs -I '{}' cat '{}' >> $CONFIG_FILE
-GATHER_SECRETS_RES=$?
-echo done
+# echo -n "Gathering all per-function secret csv files into ${ALL_SECRETS_CSV}..."
+# find $TARGET_DIR -name '*secrets.csv' -a ! -empty | xargs -I '{}' cat '{}' >> $CONFIG_FILE
+# GATHER_SECRETS_RES=$?
+# echo done
 
-if [[ $GATHER_SECRETS_RES -ne 0 ]]; then
-    echo "Error gathering all per-function secret csv files into one. $TOOLNAME exiting."
-    exit 7
-fi
+# if [[ $GATHER_SECRETS_RES -ne 0 ]]; then
+#     echo "Error gathering all per-function secret csv files into one. $TOOLNAME exiting."
+#     exit 7
+# fi
 
 # echo -n "Cleaning up per-function secret csv files..."
 # find . -name '*secrets.csv' -a ! -path "*${BUILD_DIR}*" -delete
@@ -226,12 +226,26 @@ fi
 
 echo "Starting checker on ${BIG_OBJ} using secrets file ${ALL_SECRETS_CSV}"
 echo "Start time is: $(TZ='America/Los_angeles' date +%T-%Z)"
-bap --plugin-path=$CHECKER_PLUGIN_PATH --pass=uarch-checker --no-optimization --bil-optimization=0 --uarch-checker-cs --uarch-checker-ss --uarch-checker-no-symex --uarch-checker-output-csv-file=$CHECKER_ALERTS_CSV $CHECKER_CS_FLAGS $CHECKER_SS_FLAGS --uarch-checker-config-file=$CONFIG_FILE $BIG_OBJ > $BAP_LOGS 2>&1
+echo "logging to ${BAP_LOGS}"
+bap \
+    --plugin-path=$CHECKER_PLUGIN_PATH \
+    --pass=uarch-checker \
+    --no-optimization --bil-optimization=0 \
+    --uarch-checker-output-csv-file=$CHECKER_ALERTS_CSV \
+    $CHECKER_CS_FLAGS \
+    $CHECKER_SS_FLAGS \
+    --uarch-checker-no-symex \
+    --uarch-checker-symex-profiling-output-file=./symex-profiling-data.csv \
+    --uarch-checker-config-file=$CONFIG_FILE \
+    $BIG_OBJ > $BAP_LOGS 2>&1
 echo "Done checking $BIG_OBJ at $(TZ='America/Los_angeles' date +%T-%Z)"
 
 echo -n Cleaning up build artifacts from compilation,checking pass...
 make --directory=$TARGET_DIR clean
 echo done
+
+echo "Reached point after bap call"
+# exit
 
 # TODO, this should be llc with just our passes which would get rid of our
 # need to have to play nice with the crypto lib's CFLAGS.
